GRANT CONNECT ON DATABASE url_short TO serv;

\c url_short

GRANT USAGE ON SCHEMA public TO serv;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO serv;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO serv;

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO serv;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO serv;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO serv;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO serv;